Repository ergebnis/github-changelog, pull requests merged in 2020-06, with the labels that each got.

#479 Fix: namespace case
  README.md
  github-changelog.php
Labels: bug

#480 Enhancement: Sync with ergebnis/php-library-template
  .dependabot/config.yaml
  .gitattributes
  .github/CONTRIBUTING.md
  .github/dependabot.yml
  .github/settings.yml
  .github/workflows/integrate.yaml
  .github/workflows/prune.yaml
  .github/workflows/renew.yaml
  .github/workflows/triage.yaml
  .php_cs
  Makefile
  README.md
  composer.json
  composer.lock
  infection.json
Labels: enhancement

#489 Enhancement: Synchronize with ergebnis/php-library-template
  .github/settings.yml
Labels: enhancement, merge

#503 Enhancement: Synchronize with ergebnis/php-library-template
  .github/CONTRIBUTING.md
  .github/dependabot.yml
  .github/workflows/integrate.yaml
  .github/workflows/renew.yaml
  README.md
Labels: enhancement, merge

#504 Fix: Drop support for PHP 7.2
  .github/settings.yml
  .github/workflows/integrate.yaml
  .github/workflows/renew.yaml
  .php_cs
  CHANGELOG.md
  composer.json
  composer.lock
Labels: bug, merge

#506 Fix: Drop support for PHP 7.3
  .github/settings.yml
  .github/workflows/integrate.yaml
  .github/workflows/renew.yaml
  CHANGELOG.md
  composer.json
  composer.lock
Labels: bug, merge

#508 Fix: Regenerate baseline
  psalm-baseline.xml
Labels: bug, merge

#510 Fix: Configure mutation scores via configuration file
  .github/workflows/integrate.yaml
  Makefile
  infection.json
Labels: bug, merge

#509 Enhancement: Use property type declarations where possible
  src/Console/GenerateCommand.php
  src/Repository/CommitRepository.php
  src/Repository/PullRequestRepository.php
  src/Resource/Commit.php
  src/Resource/PullRequest.php
  src/Resource/Range.php
  src/Resource/Repository.php
  src/Resource/User.php
  src/Util/RepositoryResolver.php
Labels: enhancement, merge

#511 Fix: Skip flaky test
  infection.json
  phpstan-baseline.neon
  test/Unit/Util/RepositoryResolverTest.php
Labels: bug, merge

#512 Fix: Do not import every single class
  psalm-baseline.xml
  src/Console/GenerateCommand.php
Labels: bug, merge

#513 Fix: Inject hard dependency
  github-changelog.php
  src/Console/GenerateCommand.php
  test/Unit/Console/GenerateCommandTest.php
Labels: bug, merge
